name: run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  run:
    strategy:
      matrix:
        runner-image: [macos-11, macos-12, macos-13]
    
    runs-on: ${{ matrix.runner-image }}

    steps:
    - name: checkout repository
      uses: actions/checkout@v3
    - name: compile
      run: clang++ libcxxversion.cpp -o libcxxversion
    - name: execute
      run: ./libcxxversion
