name: run

on:
  workflow_dispatch:

jobs:
  run:
    strategy:
      matrix:
        runner-image: [macos-11, macos-12, macos-13]
    
    runs-on: ${{ matrix.runner-image }}

    steps:
    - name: compile
      run: clang++ libcxxversion.cpp -o libcxxversion
    - name: execute
      run: ./libcxxversion
